### PR TITLE
Fix typo in CommandImprovements.cs

### PR DESCRIPTION
**Pull request by austinthresher**
This pull requests fixes the typo in this screenshot:
image

### CODE REVIEW

**Review by xoxfaby — APPROVED** [review]
Looks fine

**Review by xoxfaby — CHANGES_REQUESTED** [review]
Actually, you missed the ` :`

**Comment by austinthresher** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by xoxfaby — APPROVED** [review]

**Comment by xoxfaby** [comment]
idk how to get this check to rerun

**Pull request merged**
