### PR TITLE
Russian language

### PR DESCRIPTION
**Pull request by lYohl**
while learned how to work with Git, almost forgot what i was doing
all translated exept one thing
what is this?
 "BUFF_VOIDRAIDCRABWARDWIPEFOG_NAME": "Void Crab Void Void Wipe Fog"
 can't find any info on wiki

### CODE REVIEW

**Comment by xoxfaby** [comment]
> what is this?
"BUFF_VOIDRAIDCRABWARDWIPEFOG_NAME": "Void Crab Void Void Wipe Fog"
can't find any info on wiki

No clue lol

**Comment by lYohl** [comment]
will try to gang up with those void crabs
maybe it will somehow appear

**Comment by lYohl** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by xoxfaby — APPROVED** [review]
eeeeh, looks fine

**Pull request merged**
