### PR TITLE
Ukrainian Language

### PR DESCRIPTION
**Pull request by Damglador**
Some work needs to be done, but in general it is ready

### CODE REVIEW

**Review by xoxfaby — APPROVED** [review]
Looks good! 👍

**Review by xoxfaby — CHANGES_REQUESTED** [review]
Whoops, actually, this doesn't follow the format of our language files, the strings should not be nested in a "strings" dictionary.

**Comment by Damglador** [comment]
> Whoops, actually, this doesn't follow the format of our language files, the strings should not be nested in a "strings" dictionary.

**Comment by Damglador** [comment]
> Whoops, actually, this doesn't follow the format of our language files, the strings should not be nested in a "strings" dictionary.

Changed

**Review by xoxfaby — APPROVED** [review]
Obviously I can't confirm the translations but the format looks correct.

**Review by xoxfaby — APPROVED** [review]

**Review by xoxfaby — APPROVED** [review]

**Pull request merged**
