### PR TITLE
Proc coefficient fix

### PR DESCRIPTION
**Pull request by g0shu**
https://riskofrain2.gamepedia.com/Huntress#Arrow_Rain

Remove REX's default utility because that skill doesn't deal damage therefore can't proc anything anyway.

### CODE REVIEW

**Review by xoxfaby — COMMENTED** [review]
The idea was to include a proc coefficient of 0 for any abilities that directly affect enemies to make it obvious they won't proc anything, see: MUL-T utility Ram and Captain Orbital Supply Beacon.

**Comment by g0shu** [comment]
I think for those 2 examples it definitely makes sense because they deal damage, but can't proc, less so for the ones that don't deal damage? And in that case, should loader's default grapple also have 0 on it then?

**Comment by xoxfaby** [comment]
Loader's default grapple doesn't actually affect the enemy in any way.

**Comment by g0shu** [comment]
Well it still "hits" them but I'll leave it to your judgement.

**Comment by xoxfaby** [comment]
Hmm, I'm torn on this, It does "hit" them but with no actual effect, vs the Sonic Boom actually moving the enemy.

**Comment by g0shu** [comment]
I don't really know how to github, I'm not a programmer. I'm closing this but arrow rain coefficient still needs a fix.

**Comment by xoxfaby** [comment]
No problem, if you want to you can make a new pull request with just the Huntress change, otherwise I will make the change later today.

**Pull request closed without merging**
